{% set name = "psyplot" %}
{% set version = "1.4.0" %}
{% set sha256 = "d80b6dd8030ff0d2838102f6dbd2d3d4203a8493c9586f1c1b48ff961c07bd1e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - psyplot = psyplot.__main__:main
    - psyplot-plugin = psyplot.plugin_template:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base
    - funcargparse
    - docrep >=0.3
    - xarray >=0.17
    - pyyaml

test:
  commands:
    - psyplot --help
    - psyplot-plugin --help
  imports:
    - psyplot
    - psyplot.compat
    - psyplot.config
    - psyplot.sphinxext

about:
  home: https://github.com/psyplot/psyplot
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python package for interactive data visualization

  description: |
    psyplot is an cross-platform open source python project that mainly
    combines the plotting utilities of matplotlib and the data management of
    the xarray package and integrates them into a software that can be used via
    command-line and via a GUI.
  doc_url: https://psyplot.github.io
  dev_url: https://github.com/psyplot/psyplot

extra:
  recipe-maintainers:
    - Chilipp
